id = "pawn"
name = "Pawn"
version = "0.1.1"
schema_version = 1
authors = ["Pawn Zed Contributors"]
description = "Pawn language support for Zed, focused on SA-MP and open.mp development."
repository = "https://github.com/openmultiplayer/vscode-pawn"

[grammars.c]
repository = "https://github.com/tree-sitter/tree-sitter-c"
commit = "c9ff62c7ef293ccd6129318f638327dfd6ade7df"

[language_servers.pawn-language-server]
name = "Pawn Language Server"
languages = ["Pawn"]
