name = "Pawn"
grammar = "c"
path_suffixes = ["pwn", "inc", "pawn", "p"]
line_comments = ["//"]
block_comment = ["/*", "*/"]
tab_size = 4
hard_tabs = false

brackets = [
  { start = "{", end = "}", close = true, newline = true },
  { start = "[", end = "]", close = true, newline = false },
  { start = "(", end = ")", close = true, newline = false },
]

word_characters = ["_"]
